### ISSUE TITLE
华为云无法使用

### ISSUE THREAD

**Issue by greenbergpengliang** [wyzxxz/aksk_tool#7]
华为云无法使用

**Comment by R5MTF** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: 'okio.Buffer okio.BufferedSource.getBuffer()'
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:411)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at com.huaweicloud.sdk.core.impl.DefaultHttpListener.intercept(DefaultHttpListener.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at com.huaweicloud.sdk.core.impl.DefaultHttpClient.syncInvokeHttp(DefaultHttpClient.java:275)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:164)
	at com.huaweicloud.sdk.core.HcClient.syncInvokeHttp(HcClient.java:139)
	at com.huaweicloud.sdk.core.auth.GlobalCredentials.processAuthParams(GlobalCredentials.java:107)
	at com.huaweicloud.sdk.core.ClientBuilder.build(ClientBuilder.java:122)
	at aksk.huawei.Main.getRegionTest(Main.java:179)
	at aksk.Aksk.main(Aksk.java:114)

**Comment by wyzxxz** [comment]
jdk8，如果还不行可以留个联系方式发下AK测试下
